"use client";

import { useState } from "react";
import { useRouter } from "next/navigation";
import { selectTrustitPlan } from "../actions";

const plans = [{id:"basic",name:"Basic",price:29,tag:"For small businesses"},{id:"standard",name:"Standard",price:49,tag:"Best for growing businesses",popular:true},{id:"premium",name:"Premium",price:99,tag:"For established businesses"}];
export default function PlanPicker({selected}:{selected:string|null}) {
  const router=useRouter(); const [plan,setPlan]=useState(selected?.toLowerCase()??""); const [busy,setBusy]=useState(false); const [message,setMessage]=useState("");
  async function submit(){ if(!plan)return;setBusy(true);setMessage("");try{const result=await selectTrustitPlan(plan);if(!result.success){setMessage(result.message);return;}router.push("/register/payment");router.refresh();}catch{setMessage("We could not save your plan just now. Please try again.");}finally{setBusy(false);} }
  return <><div className="mt-7 grid gap-4 md:grid-cols-3">{plans.map(p=><label key={p.id} className={`relative flex min-h-56 cursor-pointer flex-col justify-between rounded-3xl border p-5 shadow-sm transition focus-within:ring-2 focus-within:ring-blue-300 ${plan===p.id?"border-blue-500 bg-blue-50/70 ring-2 ring-blue-100 shadow-[0_18px_40px_-28px_rgba(234,88,12,0.45)]":"border-slate-200 bg-white hover:-translate-y-0.5 hover:border-blue-200 hover:shadow-md"}`}>{p.popular&&<span className="absolute -top-3 left-5 rounded-full bg-orange-500 px-3 py-1 text-[10px] font-extrabold uppercase tracking-wider text-white shadow-sm">Most Popular</span>}<span><span className="flex items-center justify-between gap-3"><strong className="text-lg">{p.name}</strong><input type="radio" name="plan" checked={plan===p.id} onChange={()=>setPlan(p.id)} className="h-5 w-5 accent-orange-500" /></span><small className="mt-1 block text-slate-500">{p.tag}</small><span className="mt-5 block text-3xl font-extrabold">₹{p.price}<small className="ml-1 text-sm font-medium text-slate-500">/ 30 days</small></span></span><span className="mt-5 flex items-center gap-2 text-xs font-semibold text-slate-600"><span className="text-emerald-500">✓</span> QR Code <span className="text-emerald-500">✓</span> Support</span></label>)}</div><button onClick={()=>void submit()} disabled={!plan||busy} className="mt-7 min-h-13 w-full rounded-2xl bg-gradient-to-r from-orange-500 to-orange-600 px-5 py-3.5 text-sm font-bold text-white shadow-[0_14px_28px_-16px_rgba(234,88,12,0.45)] transition hover:from-orange-600 hover:to-orange-700 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-blue-700 focus-visible:ring-offset-2 disabled:opacity-50">{busy?"Saving…":"Continue to payment →"}</button>{message&&<p role="alert" className="mt-3 rounded-2xl bg-rose-50 px-4 py-3 text-sm text-rose-800">{message}</p>}</>;
}
