"use client";

import { useState } from "react";
import { useRouter } from "next/navigation";
import { selectTrustitPlan } from "../actions";

const plans = [{id:"basic",name:"Basic",price:29},{id:"standard",name:"Standard",price:49},{id:"premium",name:"Premium",price:99}];
export default function PlanPicker({selected,onContinue}:{selected:string|null;onContinue?:(plan:string)=>void}) {
  const router=useRouter(); const [plan,setPlan]=useState(selected?.toLowerCase()??""); const [busy,setBusy]=useState(false); const [message,setMessage]=useState("");
  async function submit(){ if(!plan)return;setBusy(true);setMessage("");try{const result=await selectTrustitPlan(plan);if(!result.success){setMessage(result.message);return;}if(onContinue)onContinue(plans.find(item=>item.id===plan)?.name??plan);else{router.push("/register/payment");router.refresh();}}catch{setMessage("We could not save your plan just now. Please try again.");}finally{setBusy(false);} }
  const features: Record<string,string[]> = { basic:["One QR code for your business","30 days of service","Customer rating and review flow"],standard:["Everything in Basic","Five existing QR templates","30 days of service"],premium:["Everything in Standard","Premium dashboard and QR customization","30 days of service"]};
  return <><div className="mt-7 grid gap-3">{plans.map(p=><label key={p.id} className={`flex cursor-pointer items-start justify-between gap-4 rounded-2xl border p-4 transition focus-within:ring-2 focus-within:ring-amber-300 sm:p-5 ${plan===p.id?"border-amber-500 bg-amber-50 ring-1 ring-amber-200":"border-slate-200 hover:border-slate-300"}`}><span className="flex items-start gap-3"><input type="radio" name="plan" checked={plan===p.id} onChange={()=>setPlan(p.id)} className="mt-1 h-4 w-4 accent-amber-700" /><span><strong className="block">{p.name}</strong><small className="text-slate-500">30 days · one-time payment</small><span className="mt-3 grid gap-1 text-sm text-slate-700">{features[p.id].map(item=><span key={item}>✓ {item}</span>)}</span></span></span><strong className="shrink-0">₹{p.price}</strong></label>)}</div><section className="mt-6 rounded-2xl border border-amber-200 bg-[#fffaf0] p-5"><p className="text-xs font-bold uppercase tracking-[.14em] text-amber-800">Premium · ₹99</p><h3 className="mt-2 text-xl font-semibold text-slate-950">Make Every Customer Interaction More Personal</h3><p className="mt-2 text-sm leading-6 text-slate-600">A few message ideas to inspire a personal touch:</p><div className="mt-3 grid grid-cols-2 gap-2">{["Festival wishes", "Birthday wishes", "Thank-you messages", "Special offers"].map(message => <p key={message} className="rounded-xl border border-amber-100 bg-white px-3 py-2 text-sm font-medium text-slate-700">{message}</p>)}</div><p className="mt-3 text-xs leading-5 text-slate-500">Examples only. Trustit does not currently send or schedule these messages.</p></section><button onClick={()=>void submit()} disabled={!plan||busy} className="mt-6 min-h-12 w-full rounded-xl bg-slate-900 px-5 py-3.5 text-sm font-semibold text-white transition hover:bg-slate-800 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-amber-600 focus-visible:ring-offset-2 disabled:opacity-50">{busy?"Saving…":"Continue to payment"}</button>{message&&<p role="alert" className="mt-3 rounded-xl bg-rose-50 px-4 py-3 text-sm text-rose-800">{message}</p>}</>;
}
