"use client";

import { useMemo, useState } from "react";
import { useRouter } from "next/navigation";
import { saveMerchantMessage } from "./actions";
import { suggestMessage, templatesForBusiness, type MessageCategory } from "@/lib/merchant-message-templates";

type Saved = { id:string; category:string; template_id:string; title:string; message:string; cta_text:string|null; starts_at:string|null; ends_at:string|null; updated_at:string };
const categories: MessageCategory[] = ["Festival","Offer","Announcement","New Product","Customer Appreciation","Seasonal"];
export default function MessageDesigner({ businessName,businessType,saved }: { businessName:string; businessType:string|null; saved:Saved[] }) {
  const router=useRouter();
  const templates = useMemo(() => templatesForBusiness(businessType), [businessType]);
  const [templateId,setTemplateId]=useState(templates[0]?.id ?? "universal-thanks");
  const selected=templates.find((item)=>item.id===templateId) ?? templates[0] ?? templatesForBusiness(null)[0]!;
  const [category,setCategory]=useState<MessageCategory>(selected.category);
  const [title,setTitle]=useState(selected.title); const [message,setMessage]=useState(selected.message); const [cta,setCta]=useState(selected.cta);
  const [prompt,setPrompt]=useState(""); const [startsAt,setStartsAt]=useState(""); const [endsAt,setEndsAt]=useState(""); const [error,setError]=useState(""); const [notice,setNotice]=useState(""); const [saving,setSaving]=useState(false);
  const [editingId,setEditingId]=useState<string|undefined>();
  function choose(id:string) { const item=templates.find((entry)=>entry.id===id); if(!item)return; setTemplateId(id);setCategory(item.category);setTitle(item.title);setMessage(item.message);setCta(item.cta);setNotice(""); }
  function changeCategory(next:MessageCategory) { const item=templates.find((entry)=>entry.category===next) ?? templatesForBusiness(null).find((entry)=>entry.category===next); if(!item)return; setTemplateId(item.id);setCategory(item.category);setTitle(item.title);setMessage(item.message);setCta(item.cta);setNotice(""); }
  function assist(tone:"Friendly"|"Premium"|"Festive"|"Short") { const suggestion=suggestMessage(prompt,tone);setTitle(suggestion.title);setMessage(suggestion.message);setCta(suggestion.cta); }
  function localDate(value:string|null){if(!value)return "";const date=new Date(value);date.setMinutes(date.getMinutes()-date.getTimezoneOffset());return date.toISOString().slice(0,16);}
  async function save() { setError("");setNotice(""); if(startsAt&&endsAt&&Date.parse(endsAt)<=Date.parse(startsAt)){setError("End date must be after the start date.");return;} setSaving(true);try{const result=await saveMerchantMessage({id:editingId,category,templateId,title,message,cta,startsAt,endsAt});if("message" in result){setError(result.message ?? "We could not save this message.");return;}setNotice(editingId?"Message updated.":"Message saved to your plans.");setEditingId(undefined);router.refresh();}finally{setSaving(false);} }
  function edit(item:Saved){setEditingId(item.id);setCategory(item.category as MessageCategory);setTemplateId(item.template_id);setTitle(item.title);setMessage(item.message);setCta(item.cta_text??"");setStartsAt(localDate(item.starts_at));setEndsAt(localDate(item.ends_at));setNotice("Editing saved message.");setError("");window.scrollTo({top:0,behavior:"smooth"});}
  async function share() { const data={title,text:`${title}\n\n${message}${cta?`\n\n${cta}`:""}`};try{if(navigator.share)await navigator.share(data);else{await navigator.clipboard.writeText(data.text);setNotice("Message copied. Choose where to share it.");}}catch{setNotice("Sharing was cancelled.");} }
  return <div className="space-y-6">
    <header><p className="text-sm font-semibold uppercase tracking-wider text-blue-700">Merchant tools</p><h1 className="mt-1 text-2xl font-bold text-slate-950">Message Designer</h1><p className="mt-2 text-sm text-slate-600">Create a message for {businessName}. Review and edit every suggestion before sharing.</p></header>
    <section className="rounded-3xl border border-slate-200 bg-white p-5 shadow-sm sm:p-7"><h2 className="text-lg font-bold text-slate-900">1 · Choose a template</h2><p className="mt-1 text-sm text-slate-500">Recommended for {businessType || "your business"}</p><div className="mt-4 grid gap-3 sm:grid-cols-2 xl:grid-cols-3">{templates.map((item)=><button type="button" key={item.id} aria-pressed={templateId===item.id} onClick={()=>choose(item.id)} className={`overflow-hidden rounded-2xl border text-left transition ${templateId===item.id?"border-amber-500 ring-2 ring-amber-200":"border-slate-200 hover:border-amber-300"}`}><div className={`bg-gradient-to-br ${item.palette} p-4 text-white`}><div className="text-xs font-bold uppercase tracking-[.2em] opacity-80">{item.motif}</div><h3 className="mt-4 text-lg font-extrabold leading-tight">{item.title}</h3><p className="mt-2 line-clamp-2 text-sm text-white/90">{item.message}</p><span className="mt-3 inline-flex rounded-full bg-white/20 px-3 py-1 text-xs font-bold">{item.cta}</span></div><div className="flex items-center justify-between bg-white px-3 py-2.5"><span><strong className="block text-sm text-slate-900">{item.name}</strong><span className="text-xs text-slate-500">{item.category} · {item.relevance}</span></span><span className="text-xs font-bold text-amber-700">{templateId===item.id?"Selected":"Choose"}</span></div></button>)}</div></section>
    <div className="grid gap-5 xl:grid-cols-[1.1fr_.9fr]">
    <section className="rounded-3xl border border-slate-200 bg-white p-5 shadow-sm sm:p-7"><h2 className="text-lg font-bold text-slate-900">2 · Edit your message</h2><label className="mt-4 block text-sm font-semibold text-slate-700">Category<select value={category} onChange={(e)=>changeCategory(e.target.value as MessageCategory)} className="mt-1.5 min-h-11 w-full rounded-xl border border-slate-200 px-3">{categories.map((item)=><option key={item}>{item}</option>)}</select></label><label className="mt-4 block text-sm font-semibold text-slate-700">Title<input value={title} maxLength={120} onChange={(e)=>setTitle(e.target.value)} className="mt-1.5 min-h-11 w-full rounded-xl border border-slate-200 px-3" /></label><label className="mt-4 block text-sm font-semibold text-slate-700">Message<textarea value={message} maxLength={2000} rows={4} onChange={(e)=>setMessage(e.target.value)} className="mt-1.5 w-full rounded-xl border border-slate-200 p-3" /></label><label className="mt-4 block text-sm font-semibold text-slate-700">Call to action (optional)<input value={cta} maxLength={80} onChange={(e)=>setCta(e.target.value)} className="mt-1.5 min-h-11 w-full rounded-xl border border-slate-200 px-3" /></label><h3 className="mt-6 font-bold text-slate-900">AI message assist</h3><p className="mt-1 text-xs text-slate-500">Suggestions stay editable and are never sent automatically.</p><textarea value={prompt} maxLength={240} onChange={(e)=>setPrompt(e.target.value)} placeholder="Diwali ke liye sweets customers ko message banana hai" rows={2} className="mt-2 w-full rounded-xl border border-slate-200 p-3 text-sm"/><div className="mt-2 flex flex-wrap gap-2">{(["Friendly","Premium","Festive","Short"] as const).map((tone)=><button type="button" onClick={()=>assist(tone)} key={tone} className="rounded-full border border-amber-200 bg-amber-50 px-3 py-1.5 text-xs font-semibold text-amber-900">{tone}</button>)}</div></section>
    <section className="space-y-4"><div className="rounded-3xl border border-slate-200 bg-white p-5 shadow-sm sm:p-7"><h2 className="text-lg font-bold text-slate-900">3 · Preview</h2><div className={`mt-4 min-h-64 rounded-3xl bg-gradient-to-br ${selected.palette} p-6 text-white shadow-lg`}><p className="text-xs font-bold uppercase tracking-[.22em] text-white/75">{category} · {businessName}</p><div className="my-7 text-3xl">{selected.motif}</div><h3 className="text-2xl font-extrabold leading-tight">{title||"Your title"}</h3><p className="mt-3 whitespace-pre-wrap text-sm leading-6 text-white/90">{message||"Your message"}</p>{cta&&<span className="mt-5 inline-flex rounded-full bg-white px-4 py-2 text-sm font-bold text-slate-900">{cta}</span>}<p className="mt-5 border-t border-white/25 pt-3 text-xs text-white/80">{endsAt?`Valid until ${new Date(endsAt).toLocaleString()}`:"Plan the dates below"}</p></div></div>
    <div className="rounded-3xl border border-slate-200 bg-white p-5 shadow-sm sm:p-7"><h2 className="text-lg font-bold text-slate-900">4 · Dates / validity</h2><label className="mt-4 block text-sm font-semibold text-slate-700">Start date and time<input type="datetime-local" value={startsAt} onChange={(e)=>setStartsAt(e.target.value)} className="mt-1.5 min-h-11 w-full rounded-xl border border-slate-200 px-3" /></label><label className="mt-4 block text-sm font-semibold text-slate-700">End date and time<input type="datetime-local" min={startsAt||undefined} value={endsAt} onChange={(e)=>setEndsAt(e.target.value)} className="mt-1.5 min-h-11 w-full rounded-xl border border-slate-200 px-3" /></label><div className="mt-5 flex flex-wrap gap-3"><button type="button" disabled={saving} onClick={save} className="min-h-11 rounded-xl bg-amber-700 px-5 font-bold text-white disabled:opacity-60">{saving?"Saving…":"5 · Save plan"}</button><button type="button" onClick={share} className="min-h-11 rounded-xl border border-slate-300 px-5 font-bold text-slate-800">Share…</button></div>{error&&<p role="alert" className="mt-3 text-sm text-rose-700">{error}</p>}{notice&&<p role="status" className="mt-3 text-sm text-emerald-700">{notice}</p>}<p className="mt-3 text-xs leading-5 text-slate-500">Sharing opens your device’s share choices, or copies the message. It does not send automatically. Offers are not linked to ratings or reviews.</p></div></section></div>
    <section className="rounded-3xl border border-slate-200 bg-white p-5 shadow-sm sm:p-7"><h2 className="text-lg font-bold text-slate-900">Saved plans</h2>{saved.length?<ul className="mt-3 divide-y divide-slate-100">{saved.map((item)=>{const now=Date.now();const state=item.ends_at&&Date.parse(item.ends_at)<now?"Expired":item.starts_at&&Date.parse(item.starts_at)>now?"Scheduled":"Valid now";return <li key={item.id} className="py-3"><strong className="text-sm text-slate-900">{item.title}</strong><span className="ml-2 rounded-full bg-slate-100 px-2 py-1 text-xs text-slate-600">{item.category}</span><span className="ml-2 rounded-full bg-emerald-50 px-2 py-1 text-xs font-semibold text-emerald-800">{state}</span><p className="mt-1 text-sm text-slate-600">{item.message}</p><p className="mt-1 text-xs text-slate-400">{item.starts_at?`Starts ${new Date(item.starts_at).toLocaleString()}`:"Unscheduled"}{item.ends_at?` · Ends ${new Date(item.ends_at).toLocaleString()}`:""}</p><button type="button" onClick={()=>edit(item)} className="mt-2 rounded-lg border border-slate-200 px-3 py-1.5 text-xs font-semibold text-slate-700">Edit plan</button></li>})}</ul>:<p className="mt-2 text-sm text-slate-500">Your saved plans will appear here.</p>}</section>
  </div>;
}
