"use client";

import {
  Armchair,
  BadgeCheck,
  BadgeIndianRupee,
  Bath,
  Bike,
  BookOpen,
  BookOpenCheck,
  BrickWall,
  BriefcaseBusiness,
  CakeSlice,
  Calculator,
  CalendarCheck,
  Camera,
  CarFront,
  CircleDot,
  Clapperboard,
  Coffee,
  Cog,
  CreditCard,
  Croissant,
  Dumbbell,
  Factory,
  Flower2,
  Fuel,
  Gamepad2,
  Gem,
  Hammer,
  HandHelping,
  HeartPulse,
  Hospital,
  Hotel,
  House,
  Lamp,
  Landmark,
  Laptop,
  LibraryBig,
  MapPin,
  Megaphone,
  MessagesSquare,
  Microscope,
  Monitor,
  Music2,
  Package,
  PackageCheck,
  Palette,
  PartyPopper,
  PawPrint,
  Pencil,
  Pill,
  Plane,
  PlugZap,
  Printer,
  Scale,
  Scissors,
  ShieldCheck,
  Shirt,
  ShoppingBag,
  Smartphone,
  Sparkles,
  Stethoscope,
  Store,
  Timer,
  Trophy,
  UsersRound,
  Utensils,
  WalletCards,
  WashingMachine,
  Waves,
  Wheat,
  Wifi,
  Wrench,
  Zap,
  type LucideIcon,
} from "lucide-react";
import { DynamicIcon, iconNames } from "lucide-react/dynamic";

const icons: Record<string, LucideIcon> = {
  Armchair,
  BadgeCheck,
  BadgeIndianRupee,
  Bath,
  Bike,
  BookOpen,
  BookOpenCheck,
  BrickWall,
  BriefcaseBusiness,
  CakeSlice,
  Calculator,
  CalendarCheck,
  Camera,
  CarFront,
  CircleDot,
  Clapperboard,
  Coffee,
  Cog,
  CreditCard,
  Croissant,
  Dumbbell,
  Factory,
  Flower2,
  Fuel,
  Gamepad2,
  Gem,
  Hammer,
  HandHelping,
  HeartPulse,
  Hospital,
  Hotel,
  House,
  Lamp,
  Landmark,
  Laptop,
  LibraryBig,
  MapPin,
  Megaphone,
  MessagesSquare,
  Microscope,
  Monitor,
  Music2,
  Package,
  PackageCheck,
  Palette,
  PartyPopper,
  PawPrint,
  Pencil,
  Pill,
  Plane,
  PlugZap,
  Printer,
  Scale,
  Scissors,
  ShieldCheck,
  Shirt,
  ShoppingBag,
  Smartphone,
  Sparkles,
  Stethoscope,
  Store,
  Timer,
  Trophy,
  UsersRound,
  Utensils,
  WalletCards,
  WashingMachine,
  Waves,
  Wheat,
  Wifi,
  Wrench,
  Zap,
};

const familyIcons: Record<string, LucideIcon> = {
  food: Utensils,
  retail: Store,
  healthcare: HeartPulse,
  education: BookOpen,
  beauty: Scissors,
  hospitality: Hotel,
  automotive: CarFront,
  home: House,
  professional: BriefcaseBusiness,
  finance: WalletCards,
  technology: Laptop,
  entertainment: Clapperboard,
  travel: Plane,
  events: PartyPopper,
  agriculture: Wheat,
  community: UsersRound,
  manufacturing: Factory,
  general: Store,
};

export default function BusinessCategoryIcon({
  name,
  family = "general",
  className = "",
}: {
  name: string;
  family?: string;
  className?: string;
}) {
  const Icon = icons[name] ?? familyIcons[family];
  if (Icon) return <Icon aria-hidden="true" focusable="false" strokeWidth={1.8} className={className} />;
  const kebab = name.replace(/([a-z0-9])([A-Z])/g, "$1-$2").toLocaleLowerCase();
  if (iconNames.includes(kebab as (typeof iconNames)[number])) return <DynamicIcon name={kebab as (typeof iconNames)[number]} aria-hidden="true" focusable="false" strokeWidth={1.8} className={className} />;
  return <Store aria-hidden="true" focusable="false" strokeWidth={1.8} className={className} />;
}
