import type { Metadata } from "next";
import { TrustitPublicPage } from "@/app/components/trustit-public-page";
import { trustitInformationMetadata, trustitPublicInfo } from "@/lib/trustit-public-info";

export const metadata: Metadata = trustitInformationMetadata({ title: "Privacy Policy | Trustit", description: "How Trustit handles merchant account, business, payment, review and optional customer information.", path: "/privacy-policy" });

export default function PrivacyPolicyPage() {
  return <TrustitPublicPage title="Privacy Policy" intro="This notice describes information handled when merchants use Trustit and customers use a Trustit review journey.">
    <p><strong>Responsible service:</strong> {trustitPublicInfo.legalName ?? "The legal operator name has not yet been configured for publication."}{trustitPublicInfo.businessAddress ? `, ${trustitPublicInfo.businessAddress}` : " The operator's postal address has not yet been configured for publication."}</p>
    <h2>Information we handle</h2><ul><li>Merchant account setup includes owner name, mobile number, password credentials managed through Supabase Auth, and business name/type, address and optional Google Review link. Structured location and optional coordinates may also be saved when a merchant provides or confirms them.</li><li>Account and service records include business status, selected plan, expiry and payment/order status.</li><li>Checkout sends the order and customer details required for payment processing to the payment provider. Card or payment instrument details are handled by that provider rather than stored as merchant profile fields by Trustit.</li><li>Customers submitting Trustit feedback provide a name, rating and review text. Customers may choose to share a mobile number and additional family or occasion details. Those optional details are stored only when the customer turns on the share-details choice.</li><li>QR scan and review-session events are used to provide the business dashboard and service functions.</li></ul>
    <h2>How information is used</h2><p>Information supports account authentication, business and QR operation, payment verification, customer review submission, merchant dashboard features, support, security and service improvement. A review draft may be generated from customer-provided words, selected experience details and rating; those draft and final review records are associated with the review session. Customer-authored feedback and rating are processed to provide the review journey and Trustit rating summaries. Customers choose whether to continue to an external Google page; Google handles that destination under its own terms and privacy practices.</p>
    <p>If a merchant chooses the optional AI QR artwork feature, the business category and design request needed to produce the artwork are sent to the image provider configured for the service. Generated artwork is stored in private application storage. Review drafts are generated using the application's local review-draft provider.</p>
    <h2>Service providers and access</h2><p>Trustit uses Supabase for authentication and application data, Vercel for hosting, and Cashfree for payment checkout and verification. Data is protected through application access controls and database policies; merchant/customer records are not intended to be publicly exposed. Information may be processed by these providers to operate their services. Review information may be accessible to the associated business through its authenticated dashboard, subject to the product's access controls.</p>
    <h2>Retention and choices</h2><p>Trustit does not currently publish a fixed retention period. Account, payment, review and security records may be retained while needed to operate the service, meet recordkeeping requirements, resolve disputes and protect the service. Optional customer contact/family/occasion details should only be submitted when the customer wants to share them. No self-service privacy-request form is currently configured.</p>
    <h2>Contact and updates</h2><p>For a privacy request or question, use the contact details on the <a href="/contact">Contact page</a>. This policy may be updated as Trustit features or applicable requirements change; the current published version applies from its publication.</p>
  </TrustitPublicPage>;
}
