export const BUSINESS_TYPES = [
  "Restaurant",
  "Cafe",
  "Coffee Shop",
  "Fast Food",
  "Bakery",
  "Cake Shop",
  "Sweet Shop",
  "Food Truck",
  "Dhaba",
  "Catering Service",
  "Grocery Store",
  "Supermarket",
  "Retail Shop",
  "Clothing Store",
  "Footwear Store",
  "Electronics Store",
  "Mobile & Accessories",
  "Hardware Store",
  "Pharmacy",
  "Clinic",
  "Medical Store",
  "Diagnostic Centre",
  "Dental Clinic",
  "Optical Store",
  "Salon",
  "Beauty Parlour",
  "Spa",
  "Barber Shop",
  "Gym & Fitness",
  "Yoga Studio",
  "Hotel",
  "Resort",
  "Guest House",
  "Travel Agency",
  "Laundry",
  "Dry Cleaning",
  "Automobile Garage",
  "Car Wash",
  "Bike Service",
  "Library",
  "Book Store",
  "Stationery Store",
  "School",
  "Coaching Centre",
  "Computer Institute",
  "Professional Services",
  "Real Estate",
  "Financial Services",
  "Insurance",
  "Pet Care",
  "Photography Studio",
  "Event Services",
  "Repair Services",
  "Other",
] as const;

export type BusinessType = (typeof BUSINESS_TYPES)[number];
