"use client";

import Link from "next/link";
import { useMemo, useState, useTransition } from "react";
import { iconNames } from "lucide-react/dynamic";
import BusinessCategoryIcon from "@/app/components/business-category-icon";
import type { AdminCategoryRecord, UnifiedBusinessCategory } from "@/lib/business-category-catalog";
import { searchUnifiedBusinessCategories } from "@/lib/business-category-catalog";
import { saveBusinessCategoryAction, setBusinessCategoryActiveAction } from "./actions";

type CategoryRow = UnifiedBusinessCategory & { id: string };
type FormValue = { id?: string; builtinEdit?: boolean; name: string; aliases: string[]; primaryIcon: string; qrIcons: string[]; experiences: { label: string; icons: string[] }[]; palette: string[]; backgroundArtDirections: string[]; designFamily: string; isActive: boolean };
const FAMILIES = ["food", "retail", "healthcare", "education", "beauty", "hospitality", "automotive", "home", "professional", "finance", "technology", "entertainment", "travel", "events", "agriculture", "community", "manufacturing", "general"];

function formFromCategory(category: CategoryRow, records: AdminCategoryRecord[]): FormValue {
  const record = records.find((entry) => entry.name.toLocaleLowerCase() === category.name.toLocaleLowerCase());
  return {
    id: record?.id,
    builtinEdit: category.source === "Built-in",
    name: category.name,
    aliases: record?.aliases ?? [],
    primaryIcon: category.primaryIcon,
    qrIcons: record?.qr_icons?.length === 3 ? record.qr_icons : category.qrIcons,
    experiences: Array.from({ length: 5 }, (_, index) => ({ label: record?.experience_mappings?.[index]?.label ?? category.themes[index]?.experiences[0]?.label ?? ["Quality", "Service", "Staff", "Cleanliness", "Overall Experience"][index], icons: record?.experience_mappings?.[index]?.icons?.slice(0, 3) ?? category.themes[index]?.experiences.map((entry) => entry.icon).slice(0, 3) ?? ["Star", "Heart", "Sparkles"] })),
    palette: record?.palette?.length === 3 ? record.palette : [...(category.themes[0]?.palette ?? ["#315b63", "#64a59e", "#ebd59b"])],
    backgroundArtDirections: record?.background_art_directions?.length === 5 ? record.background_art_directions : category.themes.map((theme) => theme.backgroundArtDirection),
    designFamily: record?.design_family ?? category.designFamily,
    isActive: category.active,
  };
}

export default function BusinessCategoryManager({ categories, counts, records = [] }: { categories: CategoryRow[]; counts: Record<string, { registered: number; active: number; inactive: number }>; records?: AdminCategoryRecord[] }) {
  const [query, setQuery] = useState("");
  const [form, setForm] = useState<FormValue | null>(null);
  const [message, setMessage] = useState("");
  const [isPending, startTransition] = useTransition();
  const visible = useMemo(() => searchUnifiedBusinessCategories(query, categories, 256), [query, categories]);

  function edit(category: CategoryRow) { setForm(formFromCategory(category, records)); setMessage(""); }
  function add() { setForm({ name: "", aliases: [], primaryIcon: "Store", qrIcons: ["Star", "Sparkles", "Heart"], experiences: ["Quality", "Service", "Staff", "Cleanliness", "Overall Experience"].map((label) => ({ label, icons: ["Star", "Heart", "Sparkles"] })), palette: ["#315b63", "#64a59e", "#ebd59b"], backgroundArtDirections: Array(5).fill("Premium local business atmosphere; keep the QR, name, and CTA area clear."), designFamily: "general", isActive: true }); setMessage(""); }
  function update<K extends keyof FormValue>(key: K, value: FormValue[K]) { setForm((current) => current ? { ...current, [key]: value } : current); }

  return <main className="mx-auto min-h-screen max-w-[1480px] space-y-5 bg-slate-50 px-4 py-6 sm:px-6 lg:px-8">
    <header className="flex flex-wrap items-end justify-between gap-4"><div><p className="text-xs font-bold uppercase tracking-[0.16em] text-blue-700">Admin Dashboard</p><h1 className="mt-1 text-3xl font-black text-slate-950">Business Categories</h1><p className="mt-2 text-sm text-slate-600">Manage the shared catalog used by registration and QR designs. Built-in canonical names stay stable.</p></div><button type="button" onClick={add} className="rounded-xl bg-blue-700 px-4 py-3 text-sm font-bold text-white shadow-sm hover:bg-blue-800">＋ Add New Business Type</button></header>
    {message && <p role="status" className="rounded-xl border border-blue-200 bg-blue-50 px-4 py-3 text-sm text-blue-900">{message}</p>}
    <section className="rounded-2xl border border-slate-200 bg-white p-4 shadow-sm"><label htmlFor="category-search" className="mb-2 block text-sm font-semibold text-slate-800">Search categories and aliases</label><input id="category-search" value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search: sal, rest, lib, hotel, petrol, tea, study…" className="w-full rounded-xl border border-slate-300 px-4 py-3 outline-none focus:border-blue-600 focus:ring-4 focus:ring-blue-100" /><p className="mt-2 text-xs text-slate-500">{visible.length} matching categories · {categories.length} total</p></section>
    <div className="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm"><div className="max-h-[68vh] overflow-auto"><table className="w-full min-w-[1020px] text-left text-sm"><thead className="sticky top-0 z-10 bg-slate-100 text-xs uppercase tracking-wide text-slate-600"><tr>{["Category", "Status", "Source", "Registered", "Active", "Inactive / Expired", "Actions"].map((label) => <th key={label} className="px-4 py-3">{label}</th>)}</tr></thead><tbody className="divide-y divide-slate-100">{visible.map((category) => { const row = category as CategoryRow; const stats = counts[row.name] ?? { registered: 0, active: 0, inactive: 0 }; return <tr key={row.name} className="hover:bg-slate-50"><td className="px-4 py-3"><span className="flex items-center gap-3"><span className="grid h-9 w-9 place-items-center rounded-xl bg-blue-50 text-blue-700"><BusinessCategoryIcon name={row.primaryIcon} family={row.designFamily} className="h-5 w-5" /></span><span><span className="block font-semibold text-slate-900">{row.name}</span><span className="text-xs text-slate-500">{row.aliases.filter((alias) => alias !== row.name).slice(0, 3).join(" · ")}</span></span></span></td><td className="px-4 py-3"><span className={`rounded-full px-2.5 py-1 text-xs font-semibold ${row.active ? "bg-emerald-50 text-emerald-700" : "bg-slate-100 text-slate-600"}`}>{row.active ? "Active" : "Inactive"}</span></td><td className="px-4 py-3 text-slate-600">{row.source}</td><td className="px-4 py-3 font-semibold">{stats.registered}</td><td className="px-4 py-3 font-semibold text-emerald-700">{stats.active}</td><td className="px-4 py-3 font-semibold text-amber-700">{stats.inactive}</td><td className="px-4 py-3"><div className="flex gap-2"><Link href={`/business-categories/${encodeURIComponent(row.slug)}`} className="rounded-lg border border-slate-300 px-2.5 py-1.5 text-xs font-semibold hover:bg-slate-50">View Businesses</Link><button onClick={() => edit(row)} className="rounded-lg border border-slate-300 px-2.5 py-1.5 text-xs font-semibold hover:bg-slate-50">Edit</button><button disabled={isPending} onClick={() => startTransition(async () => { const result = await setBusinessCategoryActiveAction(row.name, !row.active); setMessage(result.message); if (result.success) window.location.reload(); })} className="rounded-lg border border-slate-300 px-2.5 py-1.5 text-xs font-semibold hover:bg-slate-50">{row.active ? "Deactivate" : "Activate"}</button></div></td></tr>; })}</tbody></table></div></div>
    {form && <div role="dialog" aria-modal="true" aria-labelledby="category-form-title" className="fixed inset-0 z-50 overflow-y-auto bg-slate-950/40 p-4"><form onSubmit={(event) => { event.preventDefault(); startTransition(async () => { const result = await saveBusinessCategoryAction({ ...form, aliases: form.aliases }); setMessage(result.message); if (result.success) { setForm(null); window.location.reload(); } }); }} className="mx-auto my-5 max-w-4xl space-y-5 rounded-2xl bg-white p-5 shadow-2xl sm:p-7">
      <div className="flex items-start justify-between gap-3"><div><p className="text-xs font-bold uppercase tracking-wider text-blue-700">Shared category catalog</p><h2 id="category-form-title" className="mt-1 text-2xl font-black">{form.id || form.name ? `Edit ${form.name}` : "Add New Business Type"}</h2></div><button type="button" onClick={() => setForm(null)} aria-label="Close" className="rounded-lg p-2 text-2xl text-slate-500 hover:bg-slate-100">×</button></div>
      <label className="block text-sm font-semibold">Business Type Name<input required minLength={2} maxLength={80} readOnly={Boolean(form.builtinEdit)} value={form.name} onChange={(event) => update("name", event.target.value)} className="mt-1 w-full rounded-lg border border-slate-300 px-3 py-2 read-only:bg-slate-100" placeholder="e.g. Book Café" />{form.builtinEdit && <span className="mt-1 block text-xs font-normal text-slate-500">Built-in canonical names are fixed to preserve saved business types.</span>}</label>
      <label className="block text-sm font-semibold">Search Aliases <span className="font-normal text-slate-500">(comma separated)</span><input value={form.aliases.join(", ")} onChange={(event) => update("aliases", event.target.value.split(",").map((item) => item.trim()).filter(Boolean))} className="mt-1 w-full rounded-lg border border-slate-300 px-3 py-2" placeholder="short names, spellings, search phrases" /></label>
      <datalist id="lucide-icon-options">{iconNames.map((name) => <option key={name} value={name} />)}</datalist>
      <div className="grid gap-4 sm:grid-cols-2"><IconField label="Primary Category Icon" value={form.primaryIcon} onChange={(value) => update("primaryIcon", value)} /><label className="block text-sm font-semibold">Visual family<select value={form.designFamily} onChange={(event) => update("designFamily", event.target.value)} className="mt-1 w-full rounded-lg border border-slate-300 px-3 py-2">{FAMILIES.map((family) => <option key={family}>{family}</option>)}</select></label></div>
      <fieldset><legend className="text-sm font-bold">Three primary QR icons</legend><div className="mt-2 grid gap-3 sm:grid-cols-3">{form.qrIcons.map((icon, index) => <IconField key={index} label={`QR icon ${index + 1}`} value={icon} onChange={(value) => update("qrIcons", form.qrIcons.map((item, ix) => ix === index ? value : item))} />)}</div></fieldset>
      <fieldset><legend className="text-sm font-bold">Five template experiences · three icons each</legend><div className="mt-2 space-y-3">{form.experiences.map((experience, index) => <div key={index} className="grid gap-2 rounded-xl border border-slate-200 p-3 sm:grid-cols-[1fr_1fr_1fr_1fr]"><label className="text-xs font-semibold">Experience {index + 1}<input value={experience.label} maxLength={60} onChange={(event) => update("experiences", form.experiences.map((entry, ix) => ix === index ? { ...entry, label: event.target.value } : entry))} className="mt-1 w-full rounded border border-slate-300 px-2 py-2 text-sm" /></label>{experience.icons.map((icon, iconIndex) => <IconField key={iconIndex} label={`Icon ${iconIndex + 1}`} value={icon} onChange={(value) => update("experiences", form.experiences.map((entry, ix) => ix === index ? { ...entry, icons: entry.icons.map((current, ci) => ci === iconIndex ? value : current) } : entry))} />)}</div>)}</div></fieldset>
      <div><p className="text-sm font-bold">Template palette</p><div className="mt-2 flex gap-3">{form.palette.map((color, index) => <label key={index} className="text-xs font-semibold">Color {index + 1}<input type="color" value={color} onChange={(event) => update("palette", form.palette.map((item, ix) => ix === index ? event.target.value : item))} className="mt-1 block h-10 w-16 rounded border border-slate-300" /></label>)}</div></div>
      <label className="flex items-center gap-2 text-sm font-semibold"><input type="checkbox" checked={form.isActive} onChange={(event) => update("isActive", event.target.checked)} />Active and selectable for new registration</label>
      <fieldset><legend className="text-sm font-bold">Background-art direction per template</legend><div className="mt-2 grid gap-2">{form.backgroundArtDirections.map((direction, index) => <label key={index} className="text-xs font-semibold">{["Luxury", "Modern", "Nature", "Heritage", "Minimal"][index]}<input value={direction} maxLength={280} onChange={(event) => update("backgroundArtDirections", form.backgroundArtDirections.map((item, ix) => ix === index ? event.target.value : item))} className="mt-1 w-full rounded border border-slate-300 px-3 py-2 text-sm" /></label>)}</div></fieldset>
      <div className="flex justify-end gap-2"><button type="button" onClick={() => setForm(null)} className="rounded-lg border border-slate-300 px-4 py-2 text-sm font-semibold">Cancel</button><button disabled={isPending} className="rounded-lg bg-blue-700 px-5 py-2 text-sm font-bold text-white disabled:opacity-60">{isPending ? "Saving…" : "Save Category"}</button></div>
    </form></div>}
  </main>;
}

function IconField({ label, value, onChange }: { label: string; value: string; onChange: (value: string) => void }) {
  return <label className="block text-xs font-semibold">{label}<input required list="lucide-icon-options" value={value} onChange={(event) => onChange(event.target.value)} className="mt-1 w-full rounded border border-slate-300 px-2 py-2 text-sm" placeholder="Search Lucide icons" /></label>;
}
