export const BUSINESS_TYPES = [
  "Restaurant",
  "Shop",
  "Cafe",
  "Cafe/Restaurant",
  "Coffee Shop",
  "Fast Food",
  "Bakery",
  "Cake Shop",
  "Sweet Shop",
  "Food Truck",
  "Dhaba",
  "Catering Service",
  "Grocery Store",
  "Supermarket",
  "Retail Shop",
  "Retail",
  "Clothing Store",
  "Footwear Store",
  "Electronics Store",
  "Furniture Store",
  "Jewelry Store",
  "Mobile & Accessories",
  "Hardware Store",
  "Pharmacy",
  "Clinic",
  "Medical",
  "Medical Store",
  "Diagnostic Centre",
  "Dental Clinic",
  "Optical Store",
  "Salon",
  "Beauty Parlour",
  "Spa",
  "Barber Shop",
  "Gym & Fitness",
  "Yoga Studio",
  "Hotel",
  "Hotel / Stay",
  "Resort",
  "Guest House",
  "Travel Agency",
  "Laundry",
  "Dry Cleaning",
  "Automobile Garage",
  "Garage",
  "Car Wash",
  "Bike Service",
  "Library",
  "Book Store",
  "Stationery Store",
  "School",
  "Coaching Centre",
  "Computer Institute",
  "Professional Services",
  "Real Estate",
  "Financial Services",
  "Insurance",
  "Pet Care",
  "Photography Studio",
  "Event Services",
  "Repair Services",
  "Other",
  "Tea Point",
  "Tea Shop",
  "Tea Stall / Tapri",
  "Study Centre",
  "Study Room / Reading Room",
  "Petrol Pump",
  "EV Charging Station",
  "Shopping Mall",
  "General Store",
  "Namkeen Shop",
  "Beauty Salon",
  "Saloon",
  "Hospital",
  "Mobile Store",
  "Mobile Repair",
  "Computer Store",
  "Cyber Cafe",
  "Saree Shop",
  "Jewellery Store",
  "Electrical Store",
  "Sanitary Store",
  "Building Material Store",
  "Car Dealer",
  "Bike Dealer",
  "Car Service",
  "Tyre Shop",
  "Auto Parts",
  "Courier Service",
  "Printing Press",
  "Photo Studio",
  "Tailor",
  "Dry Cleaner",
  "Florist",
  "Event Planner",
  "Banquet Hall",
  "Real Estate Agency",
  "Insurance Agency",
  "Bank",
  "ATM",
  "CA Office",
  "Lawyer",
  "Digital Marketing Agency",
  "IT Services",
  "Veterinary Clinic",
  "Pet Shop",
  "Sports Store",
  "Sports Academy",
  "Dance Academy",
  "Music School",
  "Art Classes",
  "Gaming Zone",
  "Cinema",
  "Ice Cream Shop",
  "Juice Shop",
  "Food Court",
  "Pizza Shop",
  "Biryani Shop",
  "Tiffin Service",
  "Cloud Kitchen",
  "Vegetable Shop",
  "Fruit Shop",
  "Meat Shop",
  "Fish Market",
  "Dairy",
  "Water Supplier",
  "Sweet Manufacturer",
  "Packaged Food Store",
  "Organic Food Store",
  "Liquor Store",
  "Department Store",
  "Shopping Centre",
  "Online Store",
  "Gift Shop",
  "Toy Store",
  "Cosmetics Store",
  "Watch Store",
  "Optician",
  "Bag Shop",
  "Footwear Repair",
  "Textile Shop",
  "Fabric Store",
  "Curtain Store",
  "Mattress Store",
  "Kitchenware Store",
  "Home Decor Store",
  "Paint Store",
  "Glass Shop",
  "Locksmith",
  "Book Publisher",
  "Reading Room",
  "Public Library",
  "College",
  "University",
  "Preschool",
  "Play School",
  "Training Institute",
  "Language Institute",
  "Computer Training Centre",
  "Tuition Centre",
  "Skill Development Centre",
  "Hostel",
  "Nursing Home",
  "Urgent Care Centre",
  "Physiotherapy Centre",
  "Eye Hospital",
  "Eye Clinic",
  "Skin Clinic",
  "Orthopedic Clinic",
  "Maternity Clinic",
  "Pathology Lab",
  "Imaging Centre",
  "Blood Bank",
  "Vaccination Centre",
  "Health Centre",
  "Mental Health Clinic",
  "Ayurvedic Clinic",
  "Homeopathy Clinic",
  "Dental Hospital",
  "Hearing Aid Centre",
  "Optical Clinic",
  "Nutritionist",
  "Dietitian",
  "Fitness Centre",
  "Personal Trainer",
  "Pilates Studio",
  "Meditation Centre",
  "Wellness Centre",
  "Massage Centre",
  "Tattoo Studio",
  "Nail Salon",
  "Makeup Studio",
  "Bridal Studio",
  "Hair Clinic",
  "Men's Grooming",
  "Women's Boutique",
  "Homestay",
  "Lodge",
  "Service Apartment",
  "Banquet",
  "Fast Food Restaurant",
  "Canteen",
  "Cafeteria",
  "Farm",
  "Dairy Farm",
  "Poultry Farm",
  "Fish Farm",
  "Plant Nursery",
  "Seed Store",
  "Fertilizer Store",
  "Pesticide Store",
  "Agricultural Equipment Dealer",
  "Tractor Parts",
  "Farm Machinery Repair",
  "Agricultural Consultancy",
  "Veterinary Hospital",
  "Animal Feed Store",
  "Religious Institution",
  "Temple",
  "Mosque",
  "Church",
  "Gurudwara",
  "Community Centre",
  "NGO",
  "Charity",
  "Senior Care Centre",
  "Orphanage",
  "Crematorium",
  "Funeral Service",
  "Public Service Centre",
  "Manufacturing Company",
  "Textile Manufacturer",
  "Food Manufacturer",
  "Packaging Supplier",
  "Wholesale Trader",
  "Trading Company",
  "Industrial Supplier",
  "Steel Supplier",
  "Cement Distributor",
  "Import Export Company",
  "Handicraft Store",
  "Handloom Store",
  "Artisan Workshop",
  "EV Dealer",
  "EV Service Centre",
  "EV Battery Service",
  "E-commerce Service",
  "Content Creator Studio",
  "Podcast Studio",
  "Influencer Agency",
  "Online Education Platform",
  "Research Institute",
  "Daycare Centre",
  "Childcare Centre"
] as const;
export type BusinessType = (typeof BUSINESS_TYPES)[number];
export const BUSINESS_CATEGORY_COUNT = BUSINESS_TYPES.length;

export const QR_DESIGN_THEMES = [
  { id: "template_1", name: "Luxury", footer: "YOUR FEEDBACK MAKES US BETTER" },
  { id: "template_2", name: "Modern", footer: "YOUR FEEDBACK HELPS US GROW" },
  { id: "template_3", name: "Nature", footer: "YOUR EXPERIENCE MATTERS TO US" },
  { id: "template_4", name: "Heritage", footer: "YOUR REVIEW INSPIRES US TO IMPROVE" },
  { id: "template_5", name: "Minimal", footer: "YOUR FEEDBACK HELPS US SERVE YOU BETTER" },
] as const;

const familyIcons = {
  food: "Utensils", retail: "Store", healthcare: "HeartPulse", education: "BookOpen",
  beauty: "Scissors", hospitality: "Hotel", automotive: "CarFront", home: "House",
  professional: "BriefcaseBusiness", finance: "WalletCards", technology: "Laptop",
  entertainment: "Clapperboard", travel: "Plane", events: "PartyPopper",
  agriculture: "Wheat", community: "UsersRound", manufacturing: "Factory", general: "Store",
} as const;
type Family = keyof typeof familyIcons;
const paletteByFamily: Record<Family, readonly [string,string,string]> = {
  food:["#7d2946","#ed9b4c","#f7d987"], retail:["#284f52","#5b9c8b","#e4c47d"],
  healthcare:["#24616b","#58aaa6","#d9f0e9"], education:["#574338","#ad8052","#f0dfb9"],
  beauty:["#77445f","#d38a9d","#f4d6d3"], hospitality:["#234c59","#579b9a","#dfc58f"],
  automotive:["#344a5f","#5c91ad","#e2b968"], home:["#725438","#c79d66","#f1e4c9"],
  professional:["#34445e","#6b86aa","#e2c37d"], finance:["#1e5260","#61a3a0","#d4e9dc"],
  technology:["#34365f","#7283d0","#d4d9f5"], entertainment:["#663b6a","#bd6e9b","#f1c783"],
  travel:["#255c68","#64a9a3","#e8d297"], events:["#70405b","#c47791","#f3d99b"],
  agriculture:["#416540","#86a84c","#f0ca72"], community:["#41566c","#7da2aa","#e7d6ad"],
  manufacturing:["#495466","#768a9c","#d6bd8c"], general:["#315b63","#64a59e","#ebd59b"],
};
const experiences: Record<Family, readonly string[]> = {
  "food": [
    "Taste",
    "Food Quality",
    "Service",
    "Staff",
    "Cleanliness",
    "Ambience",
    "Freshness",
    "Portion",
    "Value",
    "Variety",
    "Wait Time",
    "Presentation",
    "Packaging",
    "Comfort",
    "Overall Experience"
  ],
  "retail": [
    "Product Quality",
    "Variety",
    "Staff",
    "Service",
    "Cleanliness",
    "Availability",
    "Pricing",
    "Value",
    "Display",
    "Convenience",
    "Checkout",
    "Packaging",
    "Authenticity",
    "Wait Time",
    "Overall Experience"
  ],
  "healthcare": [
    "Care Quality",
    "Doctor",
    "Staff",
    "Cleanliness",
    "Facilities",
    "Waiting Time",
    "Communication",
    "Comfort",
    "Appointment",
    "Accessibility",
    "Pharmacy",
    "Billing",
    "Safety",
    "Value",
    "Overall Experience"
  ],
  "education": [
    "Learning Experience",
    "Teaching",
    "Study Environment",
    "Seating",
    "Silence",
    "Facilities",
    "Cleanliness",
    "Staff",
    "Internet",
    "Power Backup",
    "Materials",
    "Availability",
    "Safety",
    "Value",
    "Overall Experience"
  ],
  "beauty": [
    "Service Quality",
    "Styling",
    "Staff",
    "Hygiene",
    "Products",
    "Experience",
    "Waiting Time",
    "Value",
    "Comfort",
    "Consultation",
    "Appointment",
    "Cleanliness",
    "Skill",
    "Atmosphere",
    "Overall Experience"
  ],
  "hospitality": [
    "Stay",
    "Rooms",
    "Food",
    "Cleanliness",
    "Service",
    "Staff",
    "Hospitality",
    "Comfort",
    "Location",
    "Value",
    "Facilities",
    "Booking",
    "Safety",
    "Breakfast",
    "Overall Experience"
  ],
  "automotive": [
    "Service Quality",
    "Repair Quality",
    "Staff",
    "Speed",
    "Pricing",
    "Parts",
    "Cleanliness",
    "Communication",
    "Convenience",
    "Safety",
    "Fuel Quality",
    "Payment",
    "Facilities",
    "Value",
    "Overall Experience"
  ],
  "home-services": [
    "Work Quality",
    "Timeliness",
    "Staff",
    "Communication",
    "Cleanliness",
    "Reliability",
    "Pricing",
    "Convenience",
    "Materials",
    "Safety",
    "Response Time",
    "Professionalism",
    "Value",
    "Problem Solving",
    "Overall Experience"
  ],
  "professional": [
    "Expertise",
    "Communication",
    "Staff",
    "Timeliness",
    "Professionalism",
    "Reliability",
    "Clarity",
    "Support",
    "Convenience",
    "Pricing",
    "Confidentiality",
    "Responsiveness",
    "Value",
    "Results",
    "Overall Experience"
  ],
  "finance": [
    "Service",
    "Staff",
    "Clarity",
    "Speed",
    "Security",
    "Payment",
    "Convenience",
    "Support",
    "Digital Experience",
    "Reliability",
    "Privacy",
    "Communication",
    "Pricing",
    "Value",
    "Overall Experience"
  ],
  "technology": [
    "Product Quality",
    "Technical Support",
    "Staff",
    "Speed",
    "Reliability",
    "Setup",
    "Compatibility",
    "Availability",
    "Communication",
    "Value",
    "Warranty",
    "Convenience",
    "Expertise",
    "Pricing",
    "Overall Experience"
  ],
  "entertainment": [
    "Experience",
    "Facilities",
    "Staff",
    "Cleanliness",
    "Comfort",
    "Sound",
    "Atmosphere",
    "Booking",
    "Accessibility",
    "Safety",
    "Food",
    "Value",
    "Convenience",
    "Variety",
    "Overall Experience"
  ],
  "travel": [
    "Trip Experience",
    "Booking",
    "Staff",
    "Punctuality",
    "Comfort",
    "Support",
    "Communication",
    "Safety",
    "Value",
    "Convenience",
    "Cleanliness",
    "Guidance",
    "Facilities",
    "Reliability",
    "Overall Experience"
  ],
  "events": [
    "Event Experience",
    "Planning",
    "Staff",
    "Venue",
    "Decor",
    "Food",
    "Sound",
    "Punctuality",
    "Communication",
    "Facilities",
    "Cleanliness",
    "Value",
    "Convenience",
    "Reliability",
    "Overall Experience"
  ],
  "agriculture": [
    "Product Quality",
    "Freshness",
    "Staff",
    "Availability",
    "Advice",
    "Delivery",
    "Reliability",
    "Pricing",
    "Facilities",
    "Quality",
    "Convenience",
    "Support",
    "Value",
    "Variety",
    "Overall Experience"
  ],
  "community": [
    "Service",
    "Staff",
    "Facilities",
    "Cleanliness",
    "Accessibility",
    "Safety",
    "Communication",
    "Convenience",
    "Support",
    "Atmosphere",
    "Availability",
    "Value",
    "Reliability",
    "Respect",
    "Overall Experience"
  ],
  "manufacturing": [
    "Product Quality",
    "Reliability",
    "Staff",
    "Timeliness",
    "Communication",
    "Packaging",
    "Availability",
    "Technical Support",
    "Safety",
    "Pricing",
    "Delivery",
    "Consistency",
    "Convenience",
    "Value",
    "Overall Experience"
  ],
  "general": [
    "Quality",
    "Service",
    "Staff",
    "Cleanliness",
    "Availability",
    "Convenience",
    "Pricing",
    "Communication",
    "Reliability",
    "Value",
    "Facilities",
    "Speed",
    "Comfort",
    "Support",
    "Overall Experience"
  ]
};
const rules: Array<[Family, RegExp]> = [
  ["food",/restaurant|cafe|coffee|tea|chai|food|bakery|cake|sweet|namkeen|snack|dhaba|cater|juice|ice cream|dairy|grocery|vegetable|fruit|meat|fish|water supplier|canteen|bar|pub|tiffin|kitchen/],
  ["hospitality",/hotel|stay|resort|guest house|homestay|lodge|hostel|apartment|travel|tour|taxi|bus operator|rental|visa|pilgrimage|ticket agent/],
  ["healthcare",/clinic|hospital|medical|pharmacy|diagnostic|dental|eye care|optical|physio|nursing|blood bank|health|veterinary|ambulance|dialysis|fertility|rehabilitation|hospice|hearing|nutrition|dietitian|skin care/],
  ["education",/library|book|study|school|college|university|education|coaching|training|tuition|academy|institute|class|daycare|childcare|learning|research|test preparation/],
  ["beauty",/salon|saloon|beauty|spa|barber|hair|nail|makeup|bridal|grooming|tattoo|massage/],
  ["automotive",/car|bike|automobile|auto|vehicle|tyre|tractor|petrol pump|fuel station|ev charging|charging hub|driving school/],
  ["agriculture",/farm|agricultur|nursery|seed|fertilizer|pesticide|animal feed|cattle feed/],
  ["manufacturing",/manufactur|wholesale|trading|industrial supplier|steel supplier|cement distributor|import export|packaging supplier/],
  ["finance",/bank|atm|finance|insurance|loan|credit|money transfer|stock broker|mutual fund|microfinance|payment centre|ca office|accounting|tax consultant|chartered accountant|financial consultant/],
  ["technology",/computer|cyber cafe|mobile|it services|software|web design|app development|digital services|internet service|data recovery|electronics|drone|solar|digital payment|e-commerce|content creator|podcast|influencer|social media/],
  ["retail",/store|shop|mall|market|supermarket|department|boutique|showroom|outlet|retail|florist|stationery/],
  ["home",/plumber|electrician|carpenter|painter|mason|repair|cleaning|pest control|water purifier|solar installer|interior|architect|construction|contractor|renovation|packers|security service|gardening|landscaping|housekeeping|locksmith|cleaner|key maker/],
  ["events",/event|banquet|wedding|party|conference|exhibition|tent house|decorator|catering hall|sound and lighting/],
  ["entertainment",/cinema|theatre|film|gaming|arcade|museum|gallery|amusement|water park|bowling|pool hall|sports|cricket|football|badminton|swimming|yoga|dance|music|art class|playground|adventure|escape room|concert/],
  ["professional",/professional|agency|consult|lawyer|advocate|legal|notary|real estate|recruit|employment|marketing|public relations|graphic design|translation|coworking|shared office|business centre/],
  ["community",/religious|temple|mosque|church|gurudwara|community|ngo|charity|senior care|orphanage|crematorium|funeral|public service|government office|trade association/],
];
function familyFor(name: string): Family { for(const [family,pattern] of rules) if(pattern.test(name.toLowerCase())) return family; return "general"; }
function normalize(value: string) { return value.normalize("NFKD").replace(/[\u0300-\u036f]/g,"").toLowerCase().replace(/&/g," and ").replace(/[^a-z0-9]+/g,"").trim(); }
function slugify(value: string) { return value.normalize("NFKD").replace(/[\\u0300-\\u036f]/g,"").toLowerCase().replace(/&/g," and ").replace(/[^a-z0-9]+/g,"-").replace(/^-|-$/g,""); }

const aliasesByName: Record<string,string[]> = {
  "Salon":["saloon","hair salon","beauty salon","ladies salon","mens salon","unisex salon"],
  "Restaurant":["restro","resto","dining","eatery","food restaurant"],
  "Library":["librery","reading library","public library"],
  "Study Centre":["study center","reading room","self study centre","study room"],
  "Tea Point":["tea shop","chai point","chai shop","tapri","tea corner"],
  "Tea Stall / Tapri":["chai stall","chai tapri"],
  "Petrol Pump":["fuel station","filling station","petrol station","fuel pump","petrol bunk"],
  "Shopping Mall":["mall","shopping centre","shopping center"],
  "Sweet Shop":["mithai shop","mithai store"],
  "Pharmacy":["chemist","medical shop","drug store"],
  "Mobile Store":["mobile shop","cell phone store"],
  "Mobile Repair":["mobile repair shop","phone repair"],
  "Beauty Parlour":["beauty parlor","ladies beauty parlour"],
};
const paletteDirections: Record<string,string> = {
  Luxury:"jewel-toned accents, restrained metallic highlights, and refined premium materials",
  Modern:"crisp geometry, contemporary gradients, and clean graphic shapes",
  Nature:"botanical forms, natural textures, and calm organic color",
  Heritage:"Indian craft-inspired motifs and warm traditional materials",
  Minimal:"ample negative space, simple forms, and a limited palette",
};
const artDirections: Record<Family,string> = {
  food:"appetizing ingredients and tableware",retail:"curated products or storefront details",
  healthcare:"calm care setting and soft daylight",education:"books and a quiet learning environment",
  beauty:"refined self-care details",hospitality:"welcoming destination and interior details",
  automotive:"clean vehicle or service-bay detail",home:"tasteful home details and tools",
  professional:"polished workspace",finance:"trustworthy service counter",technology:"modern devices and workspace",
  entertainment:"inviting venue detail",travel:"open travel scene",events:"restrained celebration detail",
  agriculture:"fresh crops and plant detail",community:"inclusive community gathering place",
  manufacturing:"clean workshop and product detail",general:"welcoming local business atmosphere",
};
const iconOverrides: Record<string,string> = {
  "Library":"LibraryBig","Study Centre":"BookOpenCheck","Study Room / Reading Room":"BookOpen",
  "Tea Point":"Coffee","Tea Stall / Tapri":"Coffee","Petrol Pump":"Fuel","EV Charging Station":"Zap",
  "Shopping Mall":"ShoppingBag","Sweet Shop":"CakeSlice","Restaurant":"Utensils","Cafe":"Coffee",
  "Bakery":"Croissant","Hotel":"Hotel","Salon":"Scissors","Beauty Parlour":"Sparkles",
  "Gym":"Dumbbell","Pharmacy":"Pill","Clinic":"Stethoscope","Hospital":"Hospital",
  "Diagnostic Centre":"Microscope","Mobile Store":"Smartphone","Mobile Repair":"Smartphone",
  "Computer Store":"Laptop","Cyber Cafe":"Monitor","Book Store":"BookOpen","Stationery Store":"Pencil",
  "Clothing Store":"Shirt","Saree Shop":"Shirt","Jewellery Store":"Gem","Furniture Store":"Armchair",
  "Hardware Store":"Hammer","Electrical Store":"PlugZap","Sanitary Store":"Bath",
  "Building Material Store":"BrickWall","Car Dealer":"CarFront","Bike Dealer":"Bike",
  "Car Service":"Wrench","Bike Service":"Bike","Tyre Shop":"CircleDot","Auto Parts":"Cog",
  "Car Wash":"Waves","Travel Agency":"Plane","Courier Service":"PackageCheck",
  "Printing Press":"Printer","Photo Studio":"Camera","Tailor":"Scissors","Laundry":"WashingMachine",
  "Dry Cleaner":"WashingMachine","Florist":"Flower2","Event Planner":"PartyPopper",
  "Banquet Hall":"PartyPopper","Real Estate Agency":"House","Insurance Agency":"ShieldCheck",
  "Bank":"Landmark","ATM":"CreditCard","CA Office":"Calculator","Lawyer":"Scale",
  "Digital Marketing Agency":"Megaphone","IT Services":"Laptop","Veterinary Clinic":"PawPrint",
  "Pet Shop":"PawPrint","Sports Store":"Trophy","Sports Academy":"Trophy","Dance Academy":"Music2",
  "Music School":"Music2","Art Classes":"Palette","Gaming Zone":"Gamepad2","Cinema":"Clapperboard",
};
const themeArt: Record<Family,string> = {
  food:"appetizing ingredients and tableware",retail:"curated products or storefront details",
  healthcare:"calm care setting and soft daylight",education:"books and a quiet learning environment",
  beauty:"refined self-care details",hospitality:"welcoming destination and interior details",
  automotive:"clean vehicle or service-bay detail",home:"tasteful home details and tools",
  professional:"polished workspace",finance:"trustworthy service counter",technology:"modern devices and workspace",
  entertainment:"inviting venue detail",travel:"open travel scene",events:"restrained celebration detail",
  agriculture:"fresh crops and plant detail",community:"inclusive community gathering place",
  manufacturing:"clean workshop and product detail",general:"welcoming local business atmosphere",
};
export const BUSINESS_CATALOG = BUSINESS_TYPES.map((name) => {
  const family = familyFor(name);
  const aliases = [...new Set([name,...(aliasesByName[name]??[])])];
  const categoryExperiences = experiences[family];
  const themes = QR_DESIGN_THEMES.map((theme,index)=>({
    ...theme,
    palette:paletteByFamily[family],
    experiences:categoryExperiences.slice(index*3,index*3+3),
    backgroundArtDirection:`${paletteDirections[theme.name]}; ${themeArt[family]}. Keep the QR quiet zone, business-name panel, and CTA clear.`,
  }));
  return {id:slugify(name),name,slug:slugify(name),aliases,searchTerms:[...new Set([name,...aliases,name.replace(/\bcentre\b/gi,"center"),name.replace(/\bshop\b/gi,"store")])],primaryIcon:iconOverrides[name]??familyIcons[family],designFamily:family,experiences:categoryExperiences,themes};
});
export function getBusinessCategory(value: string|null|undefined) {
  const query=normalize(String(value??""));
  return BUSINESS_CATALOG.find((category)=>normalize(category.name)===query)
    ?? BUSINESS_CATALOG.find((category)=>category.aliases.some((alias)=>normalize(alias)===query));
}
function distance(a:string,b:string):number {
  if(Math.abs(a.length-b.length)>2)return 3;
  const row=Array.from({length:b.length+1},(_,index)=>index);
  for(let i=1;i<=a.length;i++){let diagonal=row[0];row[0]=i;for(let j=1;j<=b.length;j++){const old=row[j];row[j]=Math.min(row[j]+1,row[j-1]+1,diagonal+(a[i-1]===b[j-1]?0:1));diagonal=old;}}
  return row[b.length];
}
export function searchBusinessCategories(value:string,limit=10) {
  const query=normalize(value);
  if(!query)return BUSINESS_CATALOG.slice(0,Math.min(12,Math.max(1,limit)));
  return BUSINESS_CATALOG.map((category)=>{
    const canonical=normalize(category.name), names=[...category.aliases,...category.searchTerms].map(normalize);
    let rank=99;
    if(canonical===query)rank=0;
    else if(category.aliases.some((alias)=>normalize(alias)===query))rank=1;
    else if([canonical,...names].some((item)=>item.startsWith(query)))rank=2;
    else if([canonical,...names].some((item)=>item.includes(query)))rank=3;
    else if(query.length>=4&&Math.min(...[canonical,...names].map((item)=>distance(query,item)))<=1)rank=4;
    else if(query.length>=7&&Math.min(...[canonical,...names].map((item)=>distance(query,item)))<=2)rank=5;
    return {category,rank};
  }).filter(({rank})=>rank<99).sort((a,b)=>a.rank-b.rank||a.category.name.localeCompare(b.category.name))
    .slice(0,Math.min(20,Math.max(1,limit))).map(({category})=>category);
}
export function validateBusinessCatalog() {
  const idSet=new Set<string>(),nameSet=new Set<string>(),slugSet=new Set<string>();
  return BUSINESS_CATALOG.every((category)=>{
    if(idSet.has(category.id)||nameSet.has(normalize(category.name))||slugSet.has(category.slug)||!category.aliases.length||!category.primaryIcon||category.themes.length!==5||category.experiences.length!==15)return false;
    idSet.add(category.id);nameSet.add(normalize(category.name));slugSet.add(category.slug);
    return category.themes.every((theme)=>theme.experiences.length===3&&theme.palette.length===3&&theme.backgroundArtDirection.length>0);
  });
}
